### ISSUE TITLE
Support Cloud Extension Pack

### ISSUE THREAD

**Issue by mpern** [sap-commerce-tools/commerce-gradle-plugin#14]
- new dependency
- help with configuration
- replace of extensions or change extension loading

**Comment by cristian-popa** [comment]
So I resolved the CEP automated download by adding this to my build.gradle (for now hardcoded but wanted to prove the concept) . To force the build to prefer CEP extensions over OOTB extensions just add this before HYBRIS_BIN_DIR scan path in localextensions.xml 

`<path dir='/SAPDevelop/hybris-cloud-extension-pack-1811.05/hybris/bin' autoload='false'/>` 

```
configurations {
    cep
}
.....
dependencies {
     cep group: "de.hybris.platform", name:"hybris-cloud-extension-pack", version:"1811.05", ext:'zip'
}

task installCEP(type: Sync) {
    def extractDir = "/SAPDevelop/hybris-cloud-extension-pack-1811.05"
    dependsOn configurations.cep
    from {
        configurations.cep.collect { zipTree(it) }
    }
    into extractDir
}

//call this task in the setupDev section
```

**Comment by mpern** [comment]
Check the latest release 😉
