### ISSUE TITLE
Ant tasks in camelcase not working

### ISSUE THREAD

**Issue by adrig108** [sap-commerce-tools/commerce-gradle-plugin#5]
There is an issue with ant tasks in camelCase that prevent them from being executed. Eg: `startHybrisServer` becomes `starthybrisserver`, which is not a registered task. The issue seems to be in HybrisAntRule.java. Is it required to lowercase the task name before executing it?

https://github.com/sap-commerce-tools/commerce-gradle-plugin/blob/4636d9a237b3eb9e649ae3bef14f91ab1ebf0166/src/main/java/mpern/sap/commerce/build/rules/HybrisAntRule.java#L25

Regards

**Comment by mpern** [comment]
you're right, lowercasing the target isn't correct.

(Side Note: why are you using `ant` to start hybris? it just executes `hybrisserver.sh` / `hybrisserver.bat` + the overhead of running it inside ant)

**Comment by mpern** [comment]
Fixed with version `1.21`

**Comment by adrig108** [comment]
We usually don't use ant to start the server, we just discovered the plugin and were wondering if we could avoid changing directory to the platform to start the server, as with the plugin we could compile or execute git commands directly on the hybris root dir.

And yes, I think ybp is what we were looking for. Thanks!
