### ISSUE TITLE
Issue with CCV2 and 1811

### ISSUE THREAD

**Issue by adrig108** [sap-commerce-tools/commerce-gradle-plugin#8]
Hi,

It seems SAP has changed (again) the way of versioning hybris.

While for the manifest we need to set:
`  "commerceSuiteVersion": "1811",`

On platform/build.number we get
`version=18.11`

This causes that every time we do a  `.gradlew bootstrapPlatform` the plugin detects that the version have changed:
`current version: 18.11; required version: 1811`

This happens even if we configure hybris.version in our build.gradle, so the version on the manifest seems to have preference over the configuration. IMHO, this should be the other way around. 

```
hybris {
    version = '18.11'
}
```

Regards

**Comment by mpern** [comment]
Ah great... 

Thanks for reporting, I think I have to invest some more time in determining the current version.

And yes, the version in the `manifest.json` has precedence over the configuration, maybe it should just be the default value...
